In [1559]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import seaborn as sns
from missingpy import KNNImputer
from sklearn.base import TransformerMixin
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb
import lightgbm as lgb
from sklearn.metrics import mean_squared_error
from math import sqrt 
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.linear_model import ElasticNet
from mlxtend.regressor import StackingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [1560]:
df_1=pd.read_csv('train.csv')

In [1561]:
df_1.shape

(1460, 81)

In [1562]:
df_2=pd.read_csv('test.csv')

In [1563]:
df_2.shape

(1459, 80)

In [1564]:
df=pd.concat([df_1,df_2],axis=0)

C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [1565]:
df.reset_index(drop=True,inplace=True)

In [1566]:
percent_missing = df.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'column_name': df.columns,
                                 'percent_missing': percent_missing})

In [1567]:
missing_value_df.sort_values('percent_missing',ascending=False).head(10)

               column_name  percent_missing
PoolQC              PoolQC        99.657417
MiscFeature    MiscFeature        96.402878
Alley                Alley        93.216855
Fence                Fence        80.438506
SalePrice        SalePrice        49.982871
FireplaceQu    FireplaceQu        48.646797
LotFrontage    LotFrontage        16.649538
GarageQual      GarageQual         5.447071
GarageFinish  GarageFinish         5.447071
GarageCond      GarageCond         5.447071

In [1568]:
df.drop(['PoolQC','MiscFeature','Alley','Fence','FireplaceQu'],axis=1,inplace=True)

In [1569]:
cols=df.columns

In [1570]:
num_cols = df._get_numeric_data().columns

In [1571]:
cat_cols=list(set(cols) - set(num_cols))

In [1572]:
df_cat=df[cat_cols]

In [1573]:
df_num=df[num_cols]

In [1574]:
df_num.drop(['Id'],axis=1,inplace=True)

C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [1575]:
df_cat.fillna('No_Value',inplace=True)

C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\pandas\core\frame.py:4034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

In [1576]:
num_cols=df_num.columns

In [1577]:
imputer = KNNImputer()
df_num_imputed = pd.DataFrame(imputer.fit_transform(df_num))

C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\sklearn\utils\validation.py:432: DeprecationWarning: 'warn_on_dtype' is deprecated in version 0.21 and will be removed in 0.23. Don't set `warn_on_dtype` to remove this warning.
  DeprecationWarning)
C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\sklearn\utils\validation.py:432: DeprecationWarning: 'warn_on_dtype' is deprecated in version 0.21 and will be removed in 0.23. Don't set `warn_on_dtype` to remove this warning.
  DeprecationWarning)

In [1578]:
df_num_imputed.columns=num_cols

In [1579]:
df_num_imputed.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,EnclosedPorch,...,OverallQual,PoolArea,SalePrice,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856.0,854.0,0.0,3.0,706.0,0.0,1.0,0.0,150.0,0.0,...,7.0,0.0,208500.0,0.0,8.0,856.0,0.0,2003.0,2003.0,2008.0
1,1262.0,0.0,0.0,3.0,978.0,0.0,0.0,1.0,284.0,0.0,...,6.0,0.0,181500.0,0.0,6.0,1262.0,298.0,1976.0,1976.0,2007.0
2,920.0,866.0,0.0,3.0,486.0,0.0,1.0,0.0,434.0,0.0,...,7.0,0.0,223500.0,0.0,6.0,920.0,0.0,2001.0,2002.0,2008.0
3,961.0,756.0,0.0,3.0,216.0,0.0,1.0,0.0,540.0,272.0,...,7.0,0.0,140000.0,0.0,7.0,756.0,0.0,1915.0,1970.0,2006.0
4,1145.0,1053.0,0.0,4.0,655.0,0.0,1.0,0.0,490.0,0.0,...,8.0,0.0,250000.0,0.0,9.0,1145.0,192.0,2000.0,2000.0,2008.0

In [1580]:
df_cat.isnull().any().nunique()

1

In [1581]:
df_num_imputed.any().nunique()

1

In [1582]:
df_temp=pd.DataFrame(df.astype(bool).sum(axis=0))

In [1583]:
df_temp.columns=['non_zero_values']

In [1584]:
df_temp.sort_values('non_zero_values',ascending=True).head(5)

              non_zero_values
PoolArea                   13
3SsnPorch                  37
LowQualFinSF               40
MiscVal                   103
BsmtHalfBath              177

In [1585]:
df_num_imputed.drop(['PoolArea','LowQualFinSF','MiscVal'],axis=1,inplace=True)

In [1586]:
def capping_tech_all(Df,lowerperc,higherperc):
    for col in Df.columns:
        if((col=='SalePrice') | (col=='Id')):
               continue
        percentiles = Df[col].quantile([lowerperc,higherperc]).values
        Df[col][Df[col] <= percentiles[0]] = percentiles[0]
        Df[col][Df[col] >= percentiles[1]] = percentiles[1]
    return(Df)

In [1587]:
df_capped=capping_tech_all(df_num_imputed,0.10,0.90)

In [1588]:
df_capped.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,EnclosedPorch,...,OverallCond,OverallQual,SalePrice,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856.0,854.0,0.0,3.0,706.0,0.0,1.0,0.0,150.0,0.0,...,5.0,7.0,208500.0,0.0,8.0,856.0,0.0,2003.0,2003.0,2008.0
1,1262.0,0.0,0.0,3.0,978.0,0.0,0.0,0.0,284.0,0.0,...,7.0,6.0,181500.0,0.0,6.0,1262.0,257.0,1976.0,1976.0,2007.0
2,920.0,866.0,0.0,3.0,486.0,0.0,1.0,0.0,434.0,0.0,...,5.0,7.0,223500.0,0.0,6.0,920.0,0.0,2001.0,2002.0,2008.0
3,961.0,756.0,0.0,3.0,216.0,0.0,1.0,0.0,540.0,112.0,...,5.0,7.0,140000.0,0.0,7.0,756.0,0.0,1924.0,1970.0,2006.0
4,1145.0,925.0,0.0,4.0,655.0,0.0,1.0,0.0,490.0,0.0,...,5.0,8.0,250000.0,0.0,8.0,1145.0,192.0,2000.0,2000.0,2008.0

In [1589]:
corr = df_capped.corr()
print (corr['SalePrice'].sort_values(ascending=False)[:13], '\n')
print (corr['SalePrice'].sort_values(ascending=False)[-20:])

SalePrice       1.000000
GrLivArea       0.707455
OverallQual     0.697941
GarageCars      0.668008
GarageArea      0.642905
TotalBsmtSF     0.631571
1stFlrSF        0.613673
FullBath        0.529874
YearBuilt       0.527494
GarageYrBlt     0.518343
TotRmsAbvGrd    0.509910
YearRemodAdd    0.473926
LotArea         0.473030
Name: SalePrice, dtype: float64

Fireplaces       0.465584
LotFrontage      0.420319
OpenPorchSF      0.378388
BsmtFinSF1       0.361362
WoodDeckSF       0.336729
HalfBath         0.280296
BsmtFullBath     0.246671
BedroomAbvGr     0.227082
2ndFlrSF         0.211268
BsmtUnfSF        0.167143
MoSold           0.045820
YrSold          -0.027953
MSSubClass      -0.052156
BsmtFinSF2      -0.059250
EnclosedPorch   -0.170401
OverallCond     -0.249151
3SsnPorch             NaN
BsmtHalfBath          NaN
KitchenAbvGr          NaN
ScreenPorch           NaN
Name: SalePrice, dtype: float64

In [1590]:
df_capped.drop(['MoSold','YrSold','MSSubClass','OverallCond','BsmtUnfSF','BedroomAbvGr'],axis=1,inplace=True)

In [1591]:
df_cat.head()

,BsmtFinType1,BsmtQual,LandContour,LotShape,GarageFinish,Functional,GarageQual,ExterQual,Street,Exterior1st,...,BldgType,Electrical,RoofStyle,GarageCond,BsmtCond,Neighborhood,BsmtFinType2,MasVnrType,PavedDrive,SaleCondition
0,GLQ,Gd,Lvl,Reg,RFn,Typ,TA,Gd,Pave,VinylSd,...,1Fam,SBrkr,Gable,TA,TA,CollgCr,Unf,BrkFace,Y,Normal
1,ALQ,Gd,Lvl,Reg,RFn,Typ,TA,TA,Pave,MetalSd,...,1Fam,SBrkr,Gable,TA,TA,Veenker,Unf,None,Y,Normal
2,GLQ,Gd,Lvl,IR1,RFn,Typ,TA,Gd,Pave,VinylSd,...,1Fam,SBrkr,Gable,TA,TA,CollgCr,Unf,BrkFace,Y,Normal
3,ALQ,TA,Lvl,IR1,Unf,Typ,TA,TA,Pave,Wd Sdng,...,1Fam,SBrkr,Gable,TA,Gd,Crawfor,Unf,None,Y,Abnorml
4,GLQ,Gd,Lvl,IR1,RFn,Typ,TA,Gd,Pave,VinylSd,...,1Fam,SBrkr,Gable,TA,TA,NoRidge,Unf,BrkFace,Y,Normal

In [1592]:
df_cat_dummified=pd.get_dummies(df_cat)

In [1593]:
df_cat_dummified['SalePrice'] = df_num_imputed['SalePrice']

In [1594]:
df_cat['SalePrice'] = df_num_imputed['SalePrice']

C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [1595]:
df_capped.columns

Index(['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtFullBath', 'BsmtHalfBath', 'EnclosedPorch', 'Fireplaces',
       'FullBath', 'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea',
       'HalfBath', 'KitchenAbvGr', 'LotArea', 'LotFrontage', 'MasVnrArea',
       'OpenPorchSF', 'OverallQual', 'SalePrice', 'ScreenPorch',
       'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt',
       'YearRemodAdd'],
      dtype='object')

In [1596]:
#df_cat_dummified['No_Value']

In [1597]:
df_capped.columns.unique()

Index(['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtFullBath', 'BsmtHalfBath', 'EnclosedPorch', 'Fireplaces',
       'FullBath', 'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea',
       'HalfBath', 'KitchenAbvGr', 'LotArea', 'LotFrontage', 'MasVnrArea',
       'OpenPorchSF', 'OverallQual', 'SalePrice', 'ScreenPorch',
       'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt',
       'YearRemodAdd'],
      dtype='object')

In [1598]:
df_capped.shape

(2919, 28)

In [1500]:
scaler = MinMaxScaler()

In [1599]:
df_capped['Total_sqr_footage'] = (df_capped['BsmtFinSF1'] + df_capped['BsmtFinSF2'] +
                                 df_capped['1stFlrSF'] + df_capped['2ndFlrSF'])

df_capped['Total_Bathrooms'] = (df_capped['FullBath'] + (0.5 * df_capped['HalfBath']) +
                               df_capped['BsmtFullBath'] + (0.5 * df_capped['BsmtHalfBath']))

df_capped['Total_porch_sf'] = (df_capped['OpenPorchSF'] + df_capped['3SsnPorch'] +
                              df_capped['EnclosedPorch'] + df_capped['ScreenPorch'] +
                              df_capped['WoodDeckSF'])

In [1600]:
df_capped[df_capped.columns]  = scaler.fit_transform(df_capped[df_capped.columns])

In [1601]:
df_capped.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,EnclosedPorch,Fireplaces,FullBath,...,SalePrice,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,Total_sqr_footage,Total_Bathrooms,Total_porch_sf
0,0.119544,0.923243,0.0,0.668181,0.0,1.0,0.0,0.0,0.0,1.0,...,0.241078,0.0,1.000000,0.252465,0.000000,0.963415,0.943060,0.573941,1.0,0.121951
1,0.556009,0.000000,0.0,0.925610,0.0,0.0,0.0,0.0,1.0,1.0,...,0.203583,0.0,0.333333,0.652860,1.000000,0.634146,0.462633,0.513497,0.4,0.513794
2,0.188347,0.936216,0.0,0.459966,0.0,1.0,0.0,0.0,1.0,1.0,...,0.261908,0.0,0.333333,0.315582,0.000000,0.939024,0.925267,0.524487,1.0,0.083966
3,0.232423,0.817297,0.0,0.204429,0.0,1.0,0.0,1.0,1.0,0.0,...,0.145952,0.0,0.666667,0.153846,0.000000,0.000000,0.355872,0.408064,0.4,0.293882
4,0.430230,1.000000,0.0,0.619913,0.0,1.0,0.0,0.0,1.0,1.0,...,0.298709,0.0,1.000000,0.537475,0.747082,0.926829,0.889680,0.680060,1.0,0.551779

In [1602]:
df_final=pd.concat([df_cat_dummified,df_capped],axis=1)

In [1603]:
df_final = df_final.loc[:,~df_final.columns.duplicated()]

In [1604]:
df_final.drop(['BsmtFinSF1','BsmtFinSF2','1stFlrSF','2ndFlrSF','FullBath','HalfBath','BsmtFullBath','BsmtHalfBath','OpenPorchSF','3SsnPorch','EnclosedPorch','ScreenPorch','WoodDeckSF'],axis=1,inplace=True)

In [1605]:
#features['haspool'] = features['PoolArea'].apply(lambda x: 1 if x > 0 else 0)
#features['has2ndfloor'] = features['2ndFlrSF'].apply(lambda x: 1 if x > 0 else 0)
#features['hasgarage'] = features['GarageArea'].apply(lambda x: 1 if x > 0 else 0)
#features['hasbsmt'] = features['TotalBsmtSF'].apply(lambda x: 1 if x > 0 else 0)
#features['hasfireplace'] = features['Fireplaces'].apply(lambda x: 1 if x > 0 else 0)

In [1606]:
df_final.head()

,BsmtFinType1_ALQ,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_No_Value,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,...,LotFrontage,MasVnrArea,OverallQual,TotRmsAbvGrd,TotalBsmtSF,YearBuilt,YearRemodAdd,Total_sqr_footage,Total_Bathrooms,Total_porch_sf
0,0,0,1,0,0,0,0,0,0,1,...,0.411765,0.603820,0.666667,1.000000,0.252465,0.963415,0.943060,0.573941,1.0,0.121951
1,1,0,0,0,0,0,0,0,0,1,...,0.705882,0.000000,0.333333,0.333333,0.652860,0.634146,0.462633,0.513497,0.4,0.513794
2,0,0,1,0,0,0,0,0,0,1,...,0.470588,0.499076,0.666667,0.333333,0.315582,0.939024,0.925267,0.524487,1.0,0.083966
3,1,0,0,0,0,0,0,0,0,0,...,0.313725,0.000000,0.666667,0.666667,0.153846,0.000000,0.355872,0.408064,0.4,0.293882
4,0,0,1,0,0,0,0,0,0,1,...,0.784314,1.000000,1.000000,1.000000,0.537475,0.926829,0.889680,0.680060,1.0,0.551779

In [1644]:
#X=df_final.drop(['SalePrice'],axis=1).head(1460)
X=df_final.drop(['SalePrice'],axis=1).tail(1459)

In [1638]:
y=df_final['SalePrice'].head(1460)

In [1639]:
rf = RandomForestRegressor(n_estimators=2000,max_depth=9)
#gbr=GradientBoostingRegressor(n_estimators=2000,max_depth=5)
gbr=GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05, max_depth=4, max_features='sqrt', 
 min_samples_leaf=15, min_samples_split=10, loss='huber', random_state =42)
#lightgbm = lgb.LGBMRegressor(objective='regression', 
                                      # num_leaves=4,
                                      # learning_rate=0.01, 
                                      # n_estimators=5000,
                                      # max_bin=200, 
                                      # bagging_fraction=0.75,
                                      # bagging_freq=5, 
                                      # bagging_seed=7,
                                      # feature_fraction=0.2,
                                      # feature_fraction_seed=7,
                                      # verbose=-1,)
xgboost = xgb.XGBRegressor(learning_rate=0.01,n_estimators=3460,
                                     max_depth=3, min_child_weight=0,
                                     gamma=0, subsample=0.7,
                                     colsample_bytree=0.7,
                                     objective='reg:linear', nthread=-1,
                                     scale_pos_weight=1, seed=27,
                                     reg_alpha=0.00006)
#ridge=Ridge()
#lasso=Lasso()
#elasticnet = ElasticNet()

In [1640]:
stack_gen = StackingRegressor(regressors=(rf,gbr,xgboost),
                                meta_regressor=rf,
                                use_features_in_secondary=True)
#stack_gen = StackingRegressor(regressors=(rf,gbr,xgboost,lightgbm,ridge,lasso,elasticnet),
#                                meta_regressor=xgboost,
#                                use_features_in_secondary=True)

In [1641]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [1642]:
#lr = GradientBoostingRegressor()

In [1643]:
#rf.fit(X_train,y_train)
#rf.fit(X.drop(['deviation'],axis=1),y)
#rf.fit(X,y)
stack_gen.fit(X,y)
#lr.fit(X_train,y_train)

C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \
C:\Users\ArvindBharadwajYekki\Anaconda3\lib\site-packages\xgboost\core.py:588: FutureWarning: Series.base is deprecated and will be removed in a future version
  data.base is not None and isinstance(data, np.ndarray) \

[15:32:00] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

StackingRegressor(meta_regressor=RandomForestRegressor(bootstrap=True,
                                                       criterion='mse',
                                                       max_depth=9,
                                                       max_features='auto',
                                                       max_leaf_nodes=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                                                       n_estimators=2000,
                                                       n_jobs=None,
                                                       oob_score=False,
                                                       random_state=None,
                                                       verbose=0,
                                                       warm_start=False),
                  re...
                                           colsample_bytree=0.7, gamma=0,
                                           importance_type='gain',
                                           learning_rate=0.01, max_delta_step=0,
                                           max_depth=3, min_child_weight=0,
                                           missing=None, n_estimators=3460,
                                           n_jobs=1, nthread=-1,
                                           objective='reg:linear',
                                           random_state=0, reg_alpha=6e-05,
                                           reg_lambda=1, scale_pos_weight=1,
                                           seed=27, silent=None, subsample=0.7,
                                           verbosity=1)),
                  store_train_meta_features=False,
                  use_features_in_secondary=True, verbose=0)

In [1645]:
y_pred=stack_gen.predict(X)

In [1538]:
#X['deviation']  = abs(y-y_pred)

In [869]:
#list(df_capped.columns)

['1stFlrSF',
 'BsmtFinSF1',
 'Fireplaces',
 'FullBath',
 'GarageArea',
 'GarageCars',
 'GarageYrBlt',
 'GrLivArea',
 'HalfBath',
 'KitchenAbvGr',
 'LotArea',
 'LotFrontage',
 'MasVnrArea',
 'OpenPorchSF',
 'OverallQual',
 'SalePrice',
 'ScreenPorch',
 'TotRmsAbvGrd',
 'TotalBsmtSF',
 'WoodDeckSF',
 'YearBuilt',
 'YearRemodAdd']

In [1539]:
#df_sample=pd.concat([X,y],axis=1)

In [1540]:
#df_sample.head()

,BsmtFinType1_ALQ,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_No_Value,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtQual_Ex,BsmtQual_Fa,BsmtQual_Gd,...,OverallQual,TotRmsAbvGrd,TotalBsmtSF,YearBuilt,YearRemodAdd,Total_sqr_footage,Total_Bathrooms,Total_porch_sf,deviation,SalePrice
0,0,0,1,0,0,0,0,0,0,1,...,0.666667,1.000000,0.252465,0.963415,0.943060,1.710968,2.5,0.464939,3350.245404,208500.0
1,1,0,0,0,0,0,0,0,0,1,...,0.333333,0.333333,0.652860,0.634146,0.462633,1.481620,1.0,1.000000,12939.954380,181500.0
2,0,0,1,0,0,0,0,0,0,1,...,0.666667,0.333333,0.315582,0.939024,0.925267,1.584529,2.5,0.320122,6227.021979,223500.0
3,1,0,0,0,0,0,0,0,0,0,...,0.666667,0.666667,0.153846,0.000000,0.355872,1.254150,1.0,1.266768,22308.639531,140000.0
4,0,0,1,0,0,0,0,0,0,1,...,1.000000,1.000000,0.537475,0.926829,0.889680,2.050143,2.5,1.387326,42369.179187,250000.0

In [1541]:
#df_sample=df_sample.sort_values(['deviation'],ascending=False).loc[df_sample.deviation<10000]

In [1542]:
#df_sample.shape

(944, 271)

In [1543]:
#X=df_sample.drop(['SalePrice','deviation'],axis=1)

In [1544]:
#y=df_sample['SalePrice']

In [1396]:
#df_sample.drop(df_cat_dummified.drop(['SalePrice'],axis=1).columns,axis=1).describe()

,Fireplaces,GarageArea,GarageCars,GarageYrBlt,GrLivArea,KitchenAbvGr,LotArea,LotFrontage,MasVnrArea,OverallQual,TotRmsAbvGrd,TotalBsmtSF,YearBuilt,YearRemodAdd,Total_sqr_footage,Total_Bathrooms,Total_porch_sf,deviation
count,2.0,2.0,2.0,2.000000,2.0,2.0,2.0,2.0,2.000000,2.0,2.0,2.0,2.000000,2.000000,2.0,2.000000,2.000000,2.000000
mean,1.0,1.0,1.0,0.830769,1.0,0.0,1.0,1.0,0.500000,1.0,1.0,1.0,0.865854,0.809609,3.0,2.000000,1.320490,294466.791511
std,0.0,0.0,0.0,0.021757,0.0,0.0,0.0,0.0,0.707107,0.0,0.0,0.0,0.017247,0.012582,0.0,0.707107,0.085712,30118.552904
min,1.0,1.0,1.0,0.815385,1.0,0.0,1.0,1.0,0.000000,1.0,1.0,1.0,0.853659,0.800712,3.0,1.500000,1.259882,273169.758513
25%,1.0,1.0,1.0,0.823077,1.0,0.0,1.0,1.0,0.250000,1.0,1.0,1.0,0.859756,0.805160,3.0,1.750000,1.290186,283818.275012
50%,1.0,1.0,1.0,0.830769,1.0,0.0,1.0,1.0,0.500000,1.0,1.0,1.0,0.865854,0.809609,3.0,2.000000,1.320490,294466.791511
75%,1.0,1.0,1.0,0.838462,1.0,0.0,1.0,1.0,0.750000,1.0,1.0,1.0,0.871951,0.814057,3.0,2.250000,1.350794,305115.308010
max,1.0,1.0,1.0,0.846154,1.0,0.0,1.0,1.0,1.000000,1.0,1.0,1.0,0.878049,0.818505,3.0,2.500000,1.381098,315763.824509

In [799]:
#mean_absolute_error(y_pred,y_test)

17729.935198392115

In [803]:
#(((y_pred-y_test)/y_test)*100).mean()

1.7129468282844251

In [1646]:
df_test=pd.read_csv('test.csv')

In [1647]:
#len(y_pred)

In [1648]:
df_results = pd.DataFrame({'Id':df_test['Id'],'SalePrice':list(y_pred)})

In [1649]:
df_results.shape

(1459, 2)

In [1650]:
df_results.head()

     Id      SalePrice
0  1461  112905.829801
1  1462  164545.569608
2  1463  187900.353863
3  1464  195297.446735
4  1465  174979.239167

In [1651]:
df_results.to_csv('Results.csv',index=False)